import Foundation

/// `ProfileInspector` is the read-only inverse of `ConfigBuilder`: it parses a raw
/// Xray-core JSON config into human-readable structures so a custom `Profile`'s
/// contents (outbounds → nodes, inbounds, routing, DNS) can be surfaced across the UI.
///
/// Design principles:
/// - **Never mutate the source.** The inspector only ever reads a copy of the JSON for
///   display; it does not rewrite, normalize, or import the original file. What the user
///   sees is a projection, not an edit.
/// - **Best-effort, never throwing.** A config the inspector cannot fully understand
///   still yields whatever it *could* parse (unknown outbounds become `.plain` entries
///   rather than failing the whole inspection). Returns `nil` only when the bytes are not
///   valid JSON object at all.
/// - **Mirror `ConfigBuilder`.** Field mapping (vnext/servers/streamSettings → `ProxyNode`)
///   is the exact reverse of how `ConfigBuilder` emits them, so a config generated by this
///   app round-trips back to the same node shape.
enum ProfileInspector {

    // MARK: - Result model

    /// A single parsed inbound (listening socket).
    struct Inbound: Identifiable, Hashable {
        let id = UUID()
        var tag: String?
        var proto: String
        var listen: String?
        var port: String?

        /// "socks · 127.0.0.1:1080"
        var summary: String {
            let where_ = [listen, port].compactMap { $0 }.joined(separator: ":")
            return where_.isEmpty ? proto : "\(proto) · \(where_)"
        }
    }

    /// A parsed outbound: either a recognized proxy server (mapped back to a `ProxyNode`
    /// so it renders exactly like a normal node) or a plain/utility outbound (freedom,
    /// blackhole, dns, …) we only summarize.
    enum Outbound: Identifiable, Hashable {
        case node(ProxyNode)
        case plain(id: UUID, tag: String?, proto: String)

        var id: UUID {
            switch self {
            case .node(let n): return n.id
            case .plain(let id, _, _): return id
            }
        }

        var tag: String? {
            switch self {
            case .node(let n): return n.name
            case .plain(_, let tag, _): return tag
            }
        }
    }

    /// A parsed routing rule, summarized for display.
    struct Rule: Identifiable, Hashable {
        let id = UUID()
        /// The destination: an outbound tag or "→ balancer:<tag>".
        var target: String
        /// Human-readable matcher summary ("domain: geosite:cn", "ip: geoip:private", …).
        var matcher: String
    }

    /// The full read-only projection of a config file.
    struct Inspected: Hashable {
        var inbounds: [Inbound] = []
        var outbounds: [Outbound] = []
        var domainStrategy: String?
        var rules: [Rule] = []
        var balancers: [String] = []
        var dnsServers: [String] = []
        var hasObservatory = false

        /// The first proxy outbound, used for compact one-line summaries in list rows.
        var primaryNode: ProxyNode? {
            for o in outbounds { if case .node(let n) = o { return n } }
            return nil
        }

        /// Number of recognized proxy nodes among the outbounds.
        var nodeCount: Int {
            outbounds.reduce(0) { acc, o in
                if case .node = o { return acc + 1 }
                return acc
            }
        }

        /// A short headline, e.g. "VLESS · example.com:443 · reality · 2 nodes".
        var headline: String {
            if let node = primaryNode {
                var s = node.summary
                if nodeCount > 1 { s += " · \(nodeCount) " + "nodes".localized }
                return s
            }
            if !outbounds.isEmpty { return "\(outbounds.count) " + "outbounds".localized }
            return "—"
        }
    }

    // MARK: - Entry points

    static func inspect(path: String) -> Inspected? {
        guard let data = try? Data(contentsOf: URL(fileURLWithPath: path)) else { return nil }
        return inspect(data: data)
    }

    static func inspect(data: Data) -> Inspected? {
        guard
            let root = try? JSONSerialization.jsonObject(with: data),
            let obj = root as? [String: Any]
        else { return nil }

        var result = Inspected()

        // Inbounds
        if let inbounds = obj["inbounds"] as? [[String: Any]] {
            result.inbounds = inbounds.map(parseInbound)
        }

        // Outbounds
        if let outbounds = obj["outbounds"] as? [[String: Any]] {
            result.outbounds = outbounds.map(parseOutbound)
        }

        // Routing
        if let routing = obj["routing"] as? [String: Any] {
            result.domainStrategy = string(routing["domainStrategy"])
            if let rules = routing["rules"] as? [[String: Any]] {
                result.rules = rules.compactMap(parseRule)
            }
            if let balancers = routing["balancers"] as? [[String: Any]] {
                result.balancers = balancers.compactMap { string($0["tag"]) }
            }
        }

        // DNS
        if let dns = obj["dns"] as? [String: Any], let servers = dns["servers"] as? [Any] {
            result.dnsServers = servers.compactMap { dnsServerSummary($0) }
        }

        result.hasObservatory = obj["observatory"] != nil

        return result
    }

    // MARK: - Inbounds

    private static func parseInbound(_ dict: [String: Any]) -> Inbound {
        Inbound(
            tag: string(dict["tag"]),
            proto: string(dict["protocol"]) ?? "?",
            listen: string(dict["listen"]),
            port: portString(dict["port"])
        )
    }

    // MARK: - Outbounds → ProxyNode (reverse of ConfigBuilder.buildProxyOutbound)

    private static func parseOutbound(_ dict: [String: Any]) -> Outbound {
        let proto = (string(dict["protocol"]) ?? "").lowercased()
        let tag = string(dict["tag"])
        let settings = dict["settings"] as? [String: Any] ?? [:]

        guard let mapped = ProxyProtocol(xrayOutbound: proto) else {
            return .plain(id: UUID(), tag: tag, proto: proto.isEmpty ? "?" : proto)
        }

        // The displayed name falls back to the tag, then the protocol name.
        let name = nonEmpty(tag) ?? mapped.displayName

        switch mapped {
        case .vmess, .vless:
            guard
                let vnext = (settings["vnext"] as? [[String: Any]])?.first,
                let address = string(vnext["address"])
            else { return .plain(id: UUID(), tag: tag, proto: proto) }
            var node = ProxyNode(name: name, protocolType: mapped,
                                 address: address, port: int(vnext["port"]) ?? 0)
            if let user = (vnext["users"] as? [[String: Any]])?.first {
                node.userId = string(user["id"])
                node.alterId = int(user["alterId"])
                node.encryption = string(user["security"]) ?? string(user["encryption"])
                node.flow = string(user["flow"])
            }
            applyStream(&node, dict)
            return .node(node)

        case .trojan:
            guard
                let server = (settings["servers"] as? [[String: Any]])?.first,
                let address = string(server["address"])
            else { return .plain(id: UUID(), tag: tag, proto: proto) }
            var node = ProxyNode(name: name, protocolType: .trojan,
                                 address: address, port: int(server["port"]) ?? 0)
            node.password = string(server["password"])
            node.flow = string(server["flow"])
            applyStream(&node, dict)
            return .node(node)

        case .shadowsocks:
            guard
                let server = (settings["servers"] as? [[String: Any]])?.first,
                let address = string(server["address"])
            else { return .plain(id: UUID(), tag: tag, proto: proto) }
            var node = ProxyNode(name: name, protocolType: .shadowsocks,
                                 address: address, port: int(server["port"]) ?? 0)
            node.method = string(server["method"])
            node.password = string(server["password"])
            applyStream(&node, dict)
            return .node(node)

        case .socks, .http:
            guard
                let server = (settings["servers"] as? [[String: Any]])?.first,
                let address = string(server["address"])
            else { return .plain(id: UUID(), tag: tag, proto: proto) }
            var node = ProxyNode(name: name, protocolType: mapped,
                                 address: address, port: int(server["port"]) ?? 0)
            if let cred = (server["users"] as? [[String: Any]])?.first {
                node.userId = string(cred["user"])
                node.password = string(cred["pass"])
            }
            return .node(node)

        case .wireguard:
            guard
                let peer = (settings["peers"] as? [[String: Any]])?.first,
                let endpoint = string(peer["endpoint"])
            else { return .plain(id: UUID(), tag: tag, proto: proto) }
            let (host, port) = splitEndpoint(endpoint)
            var node = ProxyNode(name: name, protocolType: .wireguard,
                                 address: host, port: port)
            node.password = string(settings["secretKey"])
            node.publicKey = string(peer["publicKey"])
            return .node(node)

        case .ssr, .hysteria2, .tuic:
            // Not produced by Xray outbounds; treat as plain if ever encountered.
            return .plain(id: UUID(), tag: tag, proto: proto)
        }
    }

    /// Reverse of `ConfigBuilder.buildStreamSettings`: read transport + security back
    /// onto the node.
    private static func applyStream(_ node: inout ProxyNode, _ outbound: [String: Any]) {
        guard let stream = outbound["streamSettings"] as? [String: Any] else { return }
        node.network = string(stream["network"]) ?? "tcp"
        node.security = string(stream["security"]) ?? "none"

        if let tls = stream["tlsSettings"] as? [String: Any] {
            node.sni = string(tls["serverName"])
            node.alpn = (tls["alpn"] as? [Any])?.compactMap { string($0) }.joined(separator: ",")
            node.fingerprint = string(tls["fingerprint"])
            node.allowInsecure = (tls["allowInsecure"] as? Bool) ?? false
        }

        if let reality = stream["realitySettings"] as? [String: Any] {
            node.sni = string(reality["serverName"])
            node.publicKey = string(reality["publicKey"])
            node.fingerprint = string(reality["fingerprint"])
            node.shortId = string(reality["shortId"])
            node.spiderX = string(reality["spiderX"])
        }

        switch node.network {
        case "ws":
            if let ws = stream["wsSettings"] as? [String: Any] {
                node.path = string(ws["path"])
                node.host = string((ws["headers"] as? [String: Any])?["Host"])
            }
        case "httpupgrade":
            if let hu = stream["httpupgradeSettings"] as? [String: Any] {
                node.path = string(hu["path"])
                node.host = string(hu["host"])
            }
        case "xhttp", "splithttp":
            if let xh = stream["xhttpSettings"] as? [String: Any] {
                node.path = string(xh["path"])
                node.host = string(xh["host"])
                node.grpcMode = string(xh["mode"])
            }
        case "grpc":
            if let g = stream["grpcSettings"] as? [String: Any] {
                node.serviceName = string(g["serviceName"])
                node.grpcMode = (g["multiMode"] as? Bool) == true ? "multi" : "gun"
            }
        case "http", "h2":
            if let h = stream["httpSettings"] as? [String: Any] {
                node.path = string(h["path"])
                node.host = (h["host"] as? [Any])?.compactMap { string($0) }.joined(separator: ",")
            }
        case "quic":
            if let q = stream["quicSettings"] as? [String: Any] {
                node.quicSecurity = string(q["security"])
                node.quicKey = string(q["key"])
                node.headerType = string((q["header"] as? [String: Any])?["type"])
            }
        case "kcp", "mkcp":
            if let k = stream["kcpSettings"] as? [String: Any] {
                node.headerType = string((k["header"] as? [String: Any])?["type"])
                node.seed = string(k["seed"])
            }
        case "tcp":
            if let tcp = stream["tcpSettings"] as? [String: Any],
               let header = tcp["header"] as? [String: Any],
               string(header["type"]) == "http" {
                node.headerType = "http"
                let request = header["request"] as? [String: Any]
                node.path = (request?["path"] as? [Any])?.compactMap { string($0) }.first
                node.host = ((request?["headers"] as? [String: Any])?["Host"] as? [Any])?
                    .compactMap { string($0) }.joined(separator: ",")
            }
        default:
            break
        }
    }

    // MARK: - Routing rules

    private static func parseRule(_ dict: [String: Any]) -> Rule? {
        let target: String
        if let balancer = string(dict["balancerTag"]) {
            target = "→ \(balancer)"
        } else if let outbound = string(dict["outboundTag"]) {
            target = outbound
        } else {
            return nil
        }

        var parts: [String] = []
        if let domains = stringList(dict["domain"]), !domains.isEmpty {
            parts.append("domain: " + domains.joined(separator: ", "))
        }
        if let ips = stringList(dict["ip"]), !ips.isEmpty {
            parts.append("ip: " + ips.joined(separator: ", "))
        }
        if let port = portString(dict["port"]) {
            parts.append("port: \(port)")
        }
        if let net = string(dict["network"]) {
            parts.append("network: \(net)")
        }
        if let inbound = stringList(dict["inboundTag"]), !inbound.isEmpty {
            parts.append("inbound: " + inbound.joined(separator: ", "))
        }

        let matcher = parts.isEmpty ? "—" : parts.joined(separator: "  ·  ")
        // Cap excessively long matcher strings so rows stay tidy.
        return Rule(target: target, matcher: String(matcher.prefix(140)))
    }

    // MARK: - DNS

    private static func dnsServerSummary(_ value: Any) -> String? {
        if let s = value as? String { return s }
        if let dict = value as? [String: Any] { return string(dict["address"]) }
        return nil
    }

    // MARK: - Coercion helpers

    private static func string(_ value: Any?) -> String? {
        if let s = value as? String { return s }
        if let n = value as? NSNumber { return n.stringValue }
        return nil
    }

    private static func nonEmpty(_ value: String?) -> String? {
        guard let v = value?.trimmingCharacters(in: .whitespaces), !v.isEmpty else { return nil }
        return v
    }

    private static func int(_ value: Any?) -> Int? {
        if let i = value as? Int { return i }
        if let n = value as? NSNumber { return n.intValue }
        if let s = value as? String { return Int(s) }
        return nil
    }

    /// A port may be an Int, a "1000-2000" range, or a "80,443" list.
    private static func portString(_ value: Any?) -> String? {
        if let i = value as? Int { return String(i) }
        if let n = value as? NSNumber { return n.stringValue }
        if let s = value as? String, !s.isEmpty { return s }
        return nil
    }

    /// Routing matchers accept either a single string or an array of strings.
    private static func stringList(_ value: Any?) -> [String]? {
        if let arr = value as? [Any] { return arr.compactMap { string($0) } }
        if let s = value as? String { return [s] }
        return nil
    }

    /// Split "host:port" (WireGuard endpoint), tolerating IPv6 in brackets.
    private static func splitEndpoint(_ endpoint: String) -> (String, Int) {
        if let colon = endpoint.lastIndex(of: ":") {
            let host = String(endpoint[..<colon])
            let port = Int(endpoint[endpoint.index(after: colon)...]) ?? 0
            return (host.trimmingCharacters(in: CharacterSet(charactersIn: "[]")), port)
        }
        return (endpoint, 0)
    }
}

private extension ProxyProtocol {
    /// Maps an Xray outbound `protocol` string to a `ProxyProtocol`, or nil for
    /// non-proxy/utility outbounds (freedom, blackhole, dns, loopback, …).
    init?(xrayOutbound proto: String) {
        switch proto {
        case "vmess": self = .vmess
        case "vless": self = .vless
        case "trojan": self = .trojan
        case "shadowsocks": self = .shadowsocks
        case "socks": self = .socks
        case "http": self = .http
        case "wireguard": self = .wireguard
        default: return nil
        }
    }
}
